-- MySQL Script generated by MySQL Workbench
-- Sun Jul  9 14:14:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8mb4 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`family` ;

CREATE TABLE IF NOT EXISTS `db`.`family` (
  `idfamily` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` BINARY(5) NOT NULL,
  `admin` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end` DATE NULL,
  PRIMARY KEY (`idfamily`),
  INDEX `fk_family_user1_idx` (`admin` ASC) VISIBLE,
  CONSTRAINT `fk_family_user1`
    FOREIGN KEY (`admin`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`s3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`s3` ;

CREATE TABLE IF NOT EXISTS `db`.`s3` (
  `idobject` INT NOT NULL AUTO_INCREMENT,
  `name` BINARY(8) NOT NULL,
  `ext` VARCHAR(10) CHARACTER SET 'utf8' NULL,
  `owner` INT NOT NULL,
  `family` INT NULL,
  PRIMARY KEY (`idobject`),
  INDEX `fk_s3_user1_idx` (`owner` ASC) VISIBLE,
  INDEX `fk_s3_family1_idx` (`family` ASC) VISIBLE,
  CONSTRAINT `fk_s3_user1`
    FOREIGN KEY (`owner`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_s3_family1`
    FOREIGN KEY (`family`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`user` ;

CREATE TABLE IF NOT EXISTS `db`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL DEFAULT '',
  `last_name` VARCHAR(255) NOT NULL DEFAULT '',
  `phone` VARCHAR(63) NOT NULL DEFAULT '',
  `birthdate` DATE NULL,
  `avatar` INT NULL,
  `theme` TINYINT NOT NULL DEFAULT 0,
  `autocorrect` TINYINT NOT NULL DEFAULT 1,
  `capitalize` TINYINT NOT NULL DEFAULT 1,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_s31_idx` (`avatar` ASC) VISIBLE,
  CONSTRAINT `fk_user_s31`
    FOREIGN KEY (`avatar`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`gazette_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`gazette_type` ;

CREATE TABLE IF NOT EXISTS `db`.`gazette_type` (
  `idgazette_type` INT NOT NULL,
  `pages` TINYINT NOT NULL,
  PRIMARY KEY (`idgazette_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`subscription_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`subscription_type` ;

CREATE TABLE IF NOT EXISTS `db`.`subscription_type` (
  `idsubscription_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `idgazette_type` INT NOT NULL,
  PRIMARY KEY (`idsubscription_type`),
  INDEX `fk_subscription_type_gazette_type1_idx` (`idgazette_type` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_type_gazette_type1`
    FOREIGN KEY (`idgazette_type`)
    REFERENCES `db`.`gazette_type` (`idgazette_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`family_has_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`family_has_member` ;

CREATE TABLE IF NOT EXISTS `db`.`family_has_member` (
  `idfamily` INT NOT NULL,
  `iduser` INT NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  INDEX `fk_family_has_member_family_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_family_has_member_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_family_has_member_family`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_has_member_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`recipient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`recipient` ;

CREATE TABLE IF NOT EXISTS `db`.`recipient` (
  `idrecipient` INT NOT NULL AUTO_INCREMENT,
  `idfamily` INT NOT NULL,
  `iduser` INT NULL,
  `display_name` VARCHAR(63) NOT NULL DEFAULT '',
  `avatar` INT NULL,
  `birthdate` DATE NOT NULL,
  `referent` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_family_has_recipient_family1_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_family_has_recipient_user1_idx` (`iduser` ASC) VISIBLE,
  PRIMARY KEY (`idrecipient`),
  INDEX `fk_recipient_user1_idx` (`referent` ASC) VISIBLE,
  INDEX `fk_recipient_s31_idx` (`avatar` ASC) VISIBLE,
  CONSTRAINT `fk_family_has_recipient_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_has_recipient_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipient_user1`
    FOREIGN KEY (`referent`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipient_s31`
    FOREIGN KEY (`avatar`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`subscription` ;

CREATE TABLE IF NOT EXISTS `db`.`subscription` (
  `idsubscription` INT NOT NULL AUTO_INCREMENT,
  `idrecipient` INT NOT NULL,
  `idsubscription_type` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idsubscription`),
  INDEX `fk_subscription_subscription_type1_idx` (`idsubscription_type` ASC) VISIBLE,
  INDEX `fk_subscription_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_subscription_type1`
    FOREIGN KEY (`idsubscription_type`)
    REFERENCES `db`.`subscription_type` (`idsubscription_type`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subscription_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `db`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`user_has_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`user_has_payment` ;

CREATE TABLE IF NOT EXISTS `db`.`user_has_payment` (
  `iduser` INT NOT NULL,
  `idsubscription` INT NULL,
  `date` DATE NOT NULL,
  `amount` DECIMAL(5,2) NOT NULL,
  `paid` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_user_has_payment_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_user_has_payment_subscription1_idx` (`idsubscription` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_payment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_payment_subscription1`
    FOREIGN KEY (`idsubscription`)
    REFERENCES `db`.`subscription` (`idsubscription`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`publication_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`publication_type` ;

CREATE TABLE IF NOT EXISTS `db`.`publication_type` (
  `idpublication_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(63) NOT NULL,
  PRIMARY KEY (`idpublication_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`layout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`layout` ;

CREATE TABLE IF NOT EXISTS `db`.`layout` (
  `idlayout` INT NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(45) NOT NULL DEFAULT 'a',
  `description` VARCHAR(45) NOT NULL DEFAULT '',
  `quantity` TINYINT NOT NULL DEFAULT 1,
  `orientation` TINYINT NOT NULL DEFAULT 0,
  `full_page` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idlayout`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`background`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`background` ;

CREATE TABLE IF NOT EXISTS `db`.`background` (
  `idbackground` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(63) NOT NULL DEFAULT '',
  `idobject` INT NOT NULL,
  `full_page` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idbackground`),
  INDEX `fk_background_s31_idx` (`idobject` ASC) VISIBLE,
  CONSTRAINT `fk_background_s31`
    FOREIGN KEY (`idobject`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`publication` ;

CREATE TABLE IF NOT EXISTS `db`.`publication` (
  `idpublication` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `idfamily` INT NOT NULL,
  `type` INT NOT NULL DEFAULT 1,
  `idlayout` INT NOT NULL DEFAULT 1,
  `idbackground` INT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `description` VARCHAR(511) NOT NULL DEFAULT '',
  `full_page` TINYINT NOT NULL DEFAULT 0,
  `global` TINYINT NOT NULL DEFAULT 1,
  `private` TINYINT NOT NULL DEFAULT 0,
  `created` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modified` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`idpublication`),
  INDEX `fk_publication_publication_type1_idx` (`type` ASC) VISIBLE,
  INDEX `fk_publication_user1_idx` (`author` ASC) VISIBLE,
  INDEX `fk_publication_family1_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_publication_layout1_idx` (`idlayout` ASC) VISIBLE,
  INDEX `fk_publication_background1_idx` (`idbackground` ASC) VISIBLE,
  CONSTRAINT `fk_publication_publication_type1`
    FOREIGN KEY (`type`)
    REFERENCES `db`.`publication_type` (`idpublication_type`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_user1`
    FOREIGN KEY (`author`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_layout1`
    FOREIGN KEY (`idlayout`)
    REFERENCES `db`.`layout` (`idlayout`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_background1`
    FOREIGN KEY (`idbackground`)
    REFERENCES `db`.`background` (`idbackground`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`movie` ;

CREATE TABLE IF NOT EXISTS `db`.`movie` (
  `idmovie` INT NOT NULL,
  `idpublication` INT NOT NULL,
  `idobject` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`idmovie`),
  INDEX `fk_movie_publication1_idx` (`idpublication` ASC) VISIBLE,
  INDEX `fk_movie_s31_idx` (`idobject` ASC) VISIBLE,
  CONSTRAINT `fk_movie_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movie_s31`
    FOREIGN KEY (`idobject`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`publication_has_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`publication_has_picture` ;

CREATE TABLE IF NOT EXISTS `db`.`publication_has_picture` (
  `idpublication` INT NOT NULL,
  `idobject` INT NOT NULL,
  `place` TINYINT NOT NULL DEFAULT 0,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  INDEX `fk_publication_has_picture_publication1_idx` (`idpublication` ASC) VISIBLE,
  INDEX `fk_publication_has_picture_s31_idx` (`idobject` ASC) VISIBLE,
  CONSTRAINT `fk_publication_has_picture_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_has_picture_s31`
    FOREIGN KEY (`idobject`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`text` ;

CREATE TABLE IF NOT EXISTS `db`.`text` (
  `idtext` INT NOT NULL AUTO_INCREMENT,
  `idpublication` INT NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`idtext`),
  INDEX `fk_text_publication1_idx` (`idpublication` ASC) VISIBLE,
  CONSTRAINT `fk_text_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`gazette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`gazette` ;

CREATE TABLE IF NOT EXISTS `db`.`gazette` (
  `idgazette` INT NOT NULL AUTO_INCREMENT,
  `idrecipient` INT NOT NULL,
  `type` INT NOT NULL DEFAULT 1,
  `cover_picture` INT NULL,
  `cover_mini` INT NULL,
  `pdf` INT NULL,
  `printed` TINYINT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `print_date` DATE NOT NULL,
  PRIMARY KEY (`idgazette`),
  INDEX `fk_gazette_s31_idx` (`pdf` ASC) VISIBLE,
  INDEX `fk_gazette_gazette_type1_idx` (`type` ASC) VISIBLE,
  INDEX `fk_gazette_s32_idx` (`cover_picture` ASC) VISIBLE,
  INDEX `fk_gazette_s33_idx` (`cover_mini` ASC) VISIBLE,
  INDEX `fk_gazette_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  CONSTRAINT `fk_gazette_s31`
    FOREIGN KEY (`pdf`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gazette_gazette_type1`
    FOREIGN KEY (`type`)
    REFERENCES `db`.`gazette_type` (`idgazette_type`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gazette_s32`
    FOREIGN KEY (`cover_picture`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gazette_s33`
    FOREIGN KEY (`cover_mini`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gazette_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `db`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`publication_has_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`publication_has_like` ;

CREATE TABLE IF NOT EXISTS `db`.`publication_has_like` (
  `idpublication` INT NOT NULL,
  `iduser` INT NOT NULL,
  INDEX `fk_publication_has_like_publication1_idx` (`idpublication` ASC) VISIBLE,
  INDEX `fk_publication_has_like_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_publication_has_like_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_has_like_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`comment` ;

CREATE TABLE IF NOT EXISTS `db`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `idpublication` INT NOT NULL,
  `iduser` INT NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `created` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modified` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comment_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_comment_publication1_idx` (`idpublication` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`comment_has_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`comment_has_like` ;

CREATE TABLE IF NOT EXISTS `db`.`comment_has_like` (
  `idcomment` INT NOT NULL,
  `iduser` INT NOT NULL,
  INDEX `fk_comment_has_like_comment1_idx` (`idcomment` ASC) VISIBLE,
  INDEX `fk_comment_has_like_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_comment_has_like_comment1`
    FOREIGN KEY (`idcomment`)
    REFERENCES `db`.`comment` (`idcomment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_has_like_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`recurring_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`recurring_payment` ;

CREATE TABLE IF NOT EXISTS `db`.`recurring_payment` (
  `iduser` INT NOT NULL,
  `idsubscription` INT NOT NULL,
  `amount` DECIMAL(5,2) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  INDEX `fk_recurring_payment_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_recurring_payment_subscription1_idx` (`idsubscription` ASC) VISIBLE,
  CONSTRAINT `fk_recurring_payment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recurring_payment_subscription1`
    FOREIGN KEY (`idsubscription`)
    REFERENCES `db`.`subscription` (`idsubscription`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`google_key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`google_key` ;

CREATE TABLE IF NOT EXISTS `db`.`google_key` (
  `idgoogle_key` BINARY(40) NOT NULL,
  `content` VARCHAR(2047) NOT NULL,
  `expiration` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idgoogle_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`firebase_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`firebase_has_user` ;

CREATE TABLE IF NOT EXISTS `db`.`firebase_has_user` (
  `idfirebase_user` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `uidfirebase` VARCHAR(63) NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  INDEX `fk_firebase_uid_user1_idx` (`iduser` ASC) VISIBLE,
  PRIMARY KEY (`idfirebase_user`),
  CONSTRAINT `fk_firebase_uid_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`default_family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`default_family` ;

CREATE TABLE IF NOT EXISTS `db`.`default_family` (
  `iduser` INT NOT NULL,
  `idfamily` INT NOT NULL,
  INDEX `fk_default_family_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_default_family_family1_idx` (`idfamily` ASC) VISIBLE,
  PRIMARY KEY (`iduser`),
  CONSTRAINT `fk_default_family_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_default_family_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`family_invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`family_invitation` ;

CREATE TABLE IF NOT EXISTS `db`.`family_invitation` (
  `idfamily` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `invitee` INT NULL,
  `inviter` INT NOT NULL,
  `approved` TINYINT NOT NULL DEFAULT 0,
  `accepted` TINYINT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_family_request_family1_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_family_invitation_user1_idx` (`inviter` ASC) VISIBLE,
  INDEX `fk_family_invitation_user2_idx` (`invitee` ASC) VISIBLE,
  CONSTRAINT `fk_family_request_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_invitation_user1`
    FOREIGN KEY (`inviter`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_invitation_user2`
    FOREIGN KEY (`invitee`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`address` ;

CREATE TABLE IF NOT EXISTS `db`.`address` (
  `idrecipient` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `phone` VARCHAR(63) NOT NULL DEFAULT '',
  `field1` VARCHAR(63) NOT NULL DEFAULT '',
  `field2` VARCHAR(63) NOT NULL DEFAULT '',
  `field3` VARCHAR(63) NOT NULL DEFAULT '',
  `postal` VARCHAR(63) NOT NULL DEFAULT '',
  `city` VARCHAR(63) NOT NULL DEFAULT '',
  `state` VARCHAR(63) NOT NULL DEFAULT '',
  `country` VARCHAR(63) NOT NULL DEFAULT '',
  PRIMARY KEY (`idrecipient`),
  INDEX `fk_address_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  CONSTRAINT `fk_address_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `db`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`family_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`family_request` ;

CREATE TABLE IF NOT EXISTS `db`.`family_request` (
  `idfamily` INT NOT NULL,
  `iduser` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_family_request_family2_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_family_request_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_family_request_family2`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_request_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`recipient_has_publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`recipient_has_publication` ;

CREATE TABLE IF NOT EXISTS `db`.`recipient_has_publication` (
  `idrecipient` INT NOT NULL,
  `idpublication` INT NOT NULL,
  INDEX `fk_recipient_has_publication_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  INDEX `fk_recipient_has_publication_publication1_idx` (`idpublication` ASC) VISIBLE,
  CONSTRAINT `fk_recipient_has_publication_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `db`.`recipient` (`idrecipient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipient_has_publication_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`unseen_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`unseen_comment` ;

CREATE TABLE IF NOT EXISTS `db`.`unseen_comment` (
  `iduser` INT NOT NULL,
  `idcomment` INT NOT NULL,
  INDEX `fk_unseen_comment_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_unseen_comment_comment1_idx` (`idcomment` ASC) VISIBLE,
  CONSTRAINT `fk_unseen_comment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_unseen_comment_comment1`
    FOREIGN KEY (`idcomment`)
    REFERENCES `db`.`comment` (`idcomment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`unseen_publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`unseen_publication` ;

CREATE TABLE IF NOT EXISTS `db`.`unseen_publication` (
  `iduser` INT NOT NULL,
  `idpublication` INT NOT NULL,
  INDEX `fk_unseen_publication_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_unseen_publication_publication1_idx` (`idpublication` ASC) VISIBLE,
  CONSTRAINT `fk_unseen_publication_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_unseen_publication_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`unseen_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`unseen_member` ;

CREATE TABLE IF NOT EXISTS `db`.`unseen_member` (
  `iduser` INT NOT NULL,
  `member` INT NOT NULL,
  `idfamily` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_unseen_member_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_unseen_member_user2_idx` (`member` ASC) VISIBLE,
  INDEX `fk_unseen_member_family1_idx` (`idfamily` ASC) VISIBLE,
  CONSTRAINT `fk_unseen_member_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_unseen_member_user2`
    FOREIGN KEY (`member`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_unseen_member_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`game_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`game_type` ;

CREATE TABLE IF NOT EXISTS `db`.`game_type` (
  `idgame_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgame_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`game_difficulty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`game_difficulty` ;

CREATE TABLE IF NOT EXISTS `db`.`game_difficulty` (
  `idgame_difficulty` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idgame_difficulty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`game` ;

CREATE TABLE IF NOT EXISTS `db`.`game` (
  `idgame` INT NOT NULL AUTO_INCREMENT,
  `idobject` INT NOT NULL,
  `type` INT NOT NULL,
  `difficulty` INT NOT NULL,
  `full_page` TINYINT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idgame`),
  INDEX `fk_game_s31_idx` (`idobject` ASC) VISIBLE,
  INDEX `fk_game_game_type1_idx` (`type` ASC) VISIBLE,
  INDEX `fk_game_game_difficulty1_idx` (`difficulty` ASC) VISIBLE,
  CONSTRAINT `fk_game_s31`
    FOREIGN KEY (`idobject`)
    REFERENCES `db`.`s3` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_game_game_type1`
    FOREIGN KEY (`type`)
    REFERENCES `db`.`game_type` (`idgame_type`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_game_game_difficulty1`
    FOREIGN KEY (`difficulty`)
    REFERENCES `db`.`game_difficulty` (`idgame_difficulty`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`song` ;

CREATE TABLE IF NOT EXISTS `db`.`song` (
  `idsong` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `link` VARCHAR(511) NULL,
  PRIMARY KEY (`idsong`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`gazette_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`gazette_page` ;

CREATE TABLE IF NOT EXISTS `db`.`gazette_page` (
  `idgazette` INT NOT NULL,
  `page_num` TINYINT NOT NULL DEFAULT 1,
  `place` TINYINT NOT NULL DEFAULT 1,
  `manual` TINYINT NOT NULL DEFAULT 0,
  `idpublication` INT NULL,
  `idgame` INT NULL,
  `idsong` INT NULL,
  INDEX `fk_gazette_page_gazette1_idx` (`idgazette` ASC) VISIBLE,
  INDEX `fk_gazette_page_publication1_idx` (`idpublication` ASC) VISIBLE,
  INDEX `fk_gazette_page_game1_idx` (`idgame` ASC) VISIBLE,
  INDEX `fk_gazette_page_song1_idx` (`idsong` ASC) VISIBLE,
  CONSTRAINT `fk_gazette_page_gazette1`
    FOREIGN KEY (`idgazette`)
    REFERENCES `db`.`gazette` (`idgazette`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gazette_page_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gazette_page_game1`
    FOREIGN KEY (`idgame`)
    REFERENCES `db`.`game` (`idgame`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gazette_page_song1`
    FOREIGN KEY (`idsong`)
    REFERENCES `db`.`song` (`idsong`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`notification` ;

CREATE TABLE IF NOT EXISTS `db`.`notification` (
  `idnotification` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT NOT NULL,
  `idfamily` INT NOT NULL,
  `notifiee` INT NOT NULL,
  `notifying` INT NULL,
  `idpublication` INT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idnotification`),
  INDEX `fk_notification_user1_idx` (`notifiee` ASC) VISIBLE,
  INDEX `fk_notification_user2_idx` (`notifying` ASC) VISIBLE,
  INDEX `fk_notification_family1_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_notification_publication1_idx` (`idpublication` ASC) VISIBLE,
  CONSTRAINT `fk_notification_user1`
    FOREIGN KEY (`notifiee`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notification_user2`
    FOREIGN KEY (`notifying`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notification_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notification_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `db`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`recipient_has_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`recipient_has_game` ;

CREATE TABLE IF NOT EXISTS `db`.`recipient_has_game` (
  `idrecipient` INT NOT NULL,
  `idgame` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_recipient_has_game_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  INDEX `fk_recipient_has_game_game1_idx` (`idgame` ASC) VISIBLE,
  CONSTRAINT `fk_recipient_has_game_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `db`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipient_has_game_game1`
    FOREIGN KEY (`idgame`)
    REFERENCES `db`.`game` (`idgame`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`recipient_has_song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`recipient_has_song` ;

CREATE TABLE IF NOT EXISTS `db`.`recipient_has_song` (
  `idrecipient` INT NOT NULL,
  `idsong` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_recipient_has_song_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  INDEX `fk_recipient_has_song_song1_idx` (`idsong` ASC) VISIBLE,
  CONSTRAINT `fk_recipient_has_song_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `db`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipient_has_song_song1`
    FOREIGN KEY (`idsong`)
    REFERENCES `db`.`song` (`idsong`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`exclude_game_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`exclude_game_type` ;

CREATE TABLE IF NOT EXISTS `db`.`exclude_game_type` (
  `idrecipient` INT NOT NULL,
  `idgame_type` INT NOT NULL,
  INDEX `fk_exclude_game_type_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  INDEX `fk_exclude_game_type_game_type1_idx` (`idgame_type` ASC) VISIBLE,
  CONSTRAINT `fk_exclude_game_type_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `db`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_exclude_game_type_game_type1`
    FOREIGN KEY (`idgame_type`)
    REFERENCES `db`.`game_type` (`idgame_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`recipent_game_difficulty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`recipent_game_difficulty` ;

CREATE TABLE IF NOT EXISTS `db`.`recipent_game_difficulty` (
  `idrecipient` INT NOT NULL,
  `idgame_type` INT NOT NULL,
  `idgame_difficulty` INT NOT NULL,
  INDEX `fk_recipent_game_difficulty_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  INDEX `fk_recipent_game_difficulty_game_type1_idx` (`idgame_type` ASC) VISIBLE,
  INDEX `fk_recipent_game_difficulty_game_difficulty1_idx` (`idgame_difficulty` ASC) VISIBLE,
  CONSTRAINT `fk_recipent_game_difficulty_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `db`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipent_game_difficulty_game_type1`
    FOREIGN KEY (`idgame_type`)
    REFERENCES `db`.`game_type` (`idgame_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipent_game_difficulty_game_difficulty1`
    FOREIGN KEY (`idgame_difficulty`)
    REFERENCES `db`.`game_difficulty` (`idgame_difficulty`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`gazette_writer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`gazette_writer` ;

CREATE TABLE IF NOT EXISTS `db`.`gazette_writer` (
  `idgazette` INT NOT NULL,
  `iduser` INT NOT NULL,
  INDEX `fk_gazette_writer_gazette1_idx` (`idgazette` ASC) VISIBLE,
  INDEX `fk_gazette_writer_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_gazette_writer_gazette1`
    FOREIGN KEY (`idgazette`)
    REFERENCES `db`.`gazette` (`idgazette`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gazette_writer_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`new_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`new_user` ;

CREATE TABLE IF NOT EXISTS `db`.`new_user` (
  `iduser` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  CONSTRAINT `fk_new_user_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`user_has_fcm_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`user_has_fcm_token` ;

CREATE TABLE IF NOT EXISTS `db`.`user_has_fcm_token` (
  `iduser` INT NOT NULL,
  `token` VARCHAR(511) CHARACTER SET 'utf8' NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_user_has_fcm_token_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_fcm_token_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`notification_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`notification_settings` ;

CREATE TABLE IF NOT EXISTS `db`.`notification_settings` (
  `iduser` INT NOT NULL,
  `newPublication` TINYINT NULL DEFAULT 1,
  `likePublication` TINYINT NULL DEFAULT 1,
  `newComment` TINYINT NULL DEFAULT 1,
  `likeComment` TINYINT NULL DEFAULT 1,
  `familyInvitation` TINYINT NULL DEFAULT 1,
  `familyMember` TINYINT NULL DEFAULT 1,
  `familyRequest` TINYINT NULL DEFAULT 1,
  `familyRequestResult` TINYINT NULL DEFAULT 1,
  `gazetPrinted` TINYINT NULL DEFAULT 1,
  `gazetLastDays` TINYINT NULL DEFAULT 1,
  `subscriptionCancelled` TINYINT NULL DEFAULT 1,
  `subscriptionBilled` TINYINT NULL DEFAULT 1,
  INDEX `fk_notification_settings_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_notification_settings_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`unseen_gazet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`unseen_gazet` ;

CREATE TABLE IF NOT EXISTS `db`.`unseen_gazet` (
  `iduser` INT NOT NULL,
  `idgazette` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_unseen_gazet_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_unseen_gazet_gazette1_idx` (`idgazette` ASC) VISIBLE,
  CONSTRAINT `fk_unseen_gazet_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_unseen_gazet_gazette1`
    FOREIGN KEY (`idgazette`)
    REFERENCES `db`.`gazette` (`idgazette`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`unseen_family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`unseen_family` ;

CREATE TABLE IF NOT EXISTS `db`.`unseen_family` (
  `iduser` INT NOT NULL,
  `idfamily` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_unseen_family_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_unseen_family_family1_idx` (`idfamily` ASC) VISIBLE,
  CONSTRAINT `fk_unseen_family_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_unseen_family_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `db`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db`.`gazette_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`gazette_type` (`idgazette_type`, `pages`) VALUES (1, 16);
INSERT INTO `db`.`gazette_type` (`idgazette_type`, `pages`) VALUES (2, 32);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`subscription_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`subscription_type` (`idsubscription_type`, `name`, `price`, `idgazette_type`) VALUES (1, 'Mensuel', 5.99, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`publication_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`publication_type` (`idpublication_type`, `name`) VALUES (1, 'journal');
INSERT INTO `db`.`publication_type` (`idpublication_type`, `name`) VALUES (2, 'pictures');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`layout`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (3, 'fj0', DEFAULT, 0, 0, 1);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (4, 'fj1', DEFAULT, 1, 0, 1);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (2, 'hj1', DEFAULT, 1, 0, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (5, 'hpl1a', DEFAULT, 1, 1, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (6, 'hpl2a', DEFAULT, 2, 1, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (7, 'hpl2b', DEFAULT, 2, 1, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (8, 'hpl2c', DEFAULT, 2, 1, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (9, 'hpl3a', DEFAULT, 3, 1, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (10, 'hpl3b', DEFAULT, 3, 1, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (11, 'hpl3c', DEFAULT, 3, 1, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (12, 'hpp1a', DEFAULT, 1, 2, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (13, 'hpp2a', DEFAULT, 2, 2, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (14, 'hpp2b', DEFAULT, 2, 2, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (15, 'hpp3a', DEFAULT, 3, 2, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (16, 'hpp3b', DEFAULT, 3, 2, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (17, 'hpp3c', DEFAULT, 3, 2, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (18, 'hpp3d', DEFAULT, 3, 2, 0);
INSERT INTO `db`.`layout` (`idlayout`, `identifier`, `description`, `quantity`, `orientation`, `full_page`) VALUES (1, 'hj0', DEFAULT, 0, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`game_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (1, 'Anagrammes');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (2, 'Mots casés');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (3, 'Mots codés');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (4, 'Mots coupés');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (5, 'Mots croisés');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (6, 'Mots fléchés');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (7, 'Mots mêlés');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (8, 'Nombres croisés');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (9, 'Pyramide');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (10, 'Quiz');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (11, 'Rikudo');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (12, 'Sudoku');
INSERT INTO `db`.`game_type` (`idgame_type`, `name`) VALUES (13, 'Wordoku');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db`.`game_difficulty`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`game_difficulty` (`idgame_difficulty`, `name`) VALUES (1, 'Trés facile');
INSERT INTO `db`.`game_difficulty` (`idgame_difficulty`, `name`) VALUES (2, 'Facile');
INSERT INTO `db`.`game_difficulty` (`idgame_difficulty`, `name`) VALUES (3, 'Moyen');
INSERT INTO `db`.`game_difficulty` (`idgame_difficulty`, `name`) VALUES (4, 'Difficile');
INSERT INTO `db`.`game_difficulty` (`idgame_difficulty`, `name`) VALUES (5, 'Très difficile');

COMMIT;

