-- MySQL Script generated by MySQL Workbench
-- Wed Jan  4 15:37:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema b2tehvmetpgbl28kakfx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b2tehvmetpgbl28kakfx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b2tehvmetpgbl28kakfx` DEFAULT CHARACTER SET utf8mb4 ;
USE `b2tehvmetpgbl28kakfx` ;

-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`user` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL DEFAULT '',
  `last_name` VARCHAR(255) NOT NULL DEFAULT '',
  `phone` VARCHAR(63) NOT NULL DEFAULT '',
  `birthday` DATE NULL,
  `avatar` VARCHAR(255) NOT NULL DEFAULT '',
  `theme` TINYINT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`subscription_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`subscription_type` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`subscription_type` (
  `idsubscription_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`idsubscription_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`family` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`family` (
  `idfamily` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `admin` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end` DATE NULL,
  PRIMARY KEY (`idfamily`),
  INDEX `fk_family_user1_idx` (`admin` ASC) VISIBLE,
  CONSTRAINT `fk_family_user1`
    FOREIGN KEY (`admin`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`family_has_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`family_has_member` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`family_has_member` (
  `idfamily` INT NOT NULL,
  `iduser` INT NOT NULL,
  INDEX `fk_family_has_member_family_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_family_has_member_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_family_has_member_family`
    FOREIGN KEY (`idfamily`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_has_member_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`address` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL DEFAULT '',
  `last_name` VARCHAR(255) NOT NULL DEFAULT '',
  `phone` VARCHAR(63) NOT NULL DEFAULT '',
  `field1` VARCHAR(63) NOT NULL DEFAULT '',
  `field2` VARCHAR(63) NOT NULL DEFAULT '',
  `field3` VARCHAR(63) NOT NULL DEFAULT '',
  `postal` VARCHAR(63) NOT NULL DEFAULT '',
  `city` VARCHAR(63) NOT NULL DEFAULT '',
  `state` VARCHAR(63) NOT NULL DEFAULT '',
  `country` VARCHAR(63) NOT NULL DEFAULT '',
  PRIMARY KEY (`idaddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`recipient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`recipient` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`recipient` (
  `idrecipient` INT NOT NULL AUTO_INCREMENT,
  `idfamily` INT NOT NULL,
  `iduser` INT NULL,
  `display_name` VARCHAR(63) NOT NULL DEFAULT '',
  `avatar` VARCHAR(255) NOT NULL DEFAULT '',
  `birth_date` DATE NOT NULL,
  `idaddress` INT NOT NULL,
  `referent` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_family_has_recipient_family1_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_family_has_recipient_user1_idx` (`iduser` ASC) VISIBLE,
  PRIMARY KEY (`idrecipient`),
  INDEX `fk_recipient_address1_idx` (`idaddress` ASC) VISIBLE,
  INDEX `fk_recipient_user1_idx` (`referent` ASC) VISIBLE,
  CONSTRAINT `fk_family_has_recipient_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_has_recipient_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipient_address1`
    FOREIGN KEY (`idaddress`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`address` (`idaddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipient_user1`
    FOREIGN KEY (`referent`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`subscription` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`subscription` (
  `idsubscription` INT NOT NULL AUTO_INCREMENT,
  `idrecipient` INT NOT NULL,
  `idsubscription_type` INT NOT NULL,
  `start` DATE NOT NULL,
  `end` DATE NULL,
  PRIMARY KEY (`idsubscription`),
  INDEX `fk_subscription_subscription_type1_idx` (`idsubscription_type` ASC) VISIBLE,
  INDEX `fk_subscription_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_subscription_type1`
    FOREIGN KEY (`idsubscription_type`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`subscription_type` (`idsubscription_type`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subscription_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`user_has_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`user_has_payment` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`user_has_payment` (
  `iduser` INT NOT NULL,
  `idsubscription` INT NOT NULL,
  `date` DATE NOT NULL,
  `amount` DECIMAL(5,2) NOT NULL,
  `paid` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_user_has_payment_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_user_has_payment_subscription1_idx` (`idsubscription` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_payment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_payment_subscription1`
    FOREIGN KEY (`idsubscription`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`subscription` (`idsubscription`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`publication_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`publication_type` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`publication_type` (
  `idpublication_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(63) NOT NULL,
  PRIMARY KEY (`idpublication_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`publication` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`publication` (
  `idpublication` INT NOT NULL AUTO_INCREMENT,
  `idpublication_type` INT NOT NULL,
  `author` INT NOT NULL,
  `idfamily` INT NOT NULL,
  `description` VARCHAR(511) NOT NULL DEFAULT '',
  `created` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modified` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`idpublication`),
  INDEX `fk_publication_publication_type1_idx` (`idpublication_type` ASC) VISIBLE,
  INDEX `fk_publication_user1_idx` (`author` ASC) VISIBLE,
  INDEX `fk_publication_family1_idx` (`idfamily` ASC) VISIBLE,
  CONSTRAINT `fk_publication_publication_type1`
    FOREIGN KEY (`idpublication_type`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`publication_type` (`idpublication_type`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_user1`
    FOREIGN KEY (`author`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`picture` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`picture` (
  `idpicture` INT NOT NULL AUTO_INCREMENT,
  `object_key` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`idpicture`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`movie` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`movie` (
  `idmovie` INT NOT NULL,
  `idpublication` INT NOT NULL,
  `object_key` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`idmovie`),
  INDEX `fk_movie_publication1_idx` (`idpublication` ASC) VISIBLE,
  CONSTRAINT `fk_movie_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`publication_has_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`publication_has_picture` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`publication_has_picture` (
  `idpublication` INT NOT NULL,
  `idpicture` INT NOT NULL,
  INDEX `fk_publication_has_picture_publication1_idx` (`idpublication` ASC) VISIBLE,
  INDEX `fk_publication_has_picture_picture1_idx` (`idpicture` ASC) VISIBLE,
  CONSTRAINT `fk_publication_has_picture_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_has_picture_picture1`
    FOREIGN KEY (`idpicture`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`picture` (`idpicture`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`text` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`text` (
  `idtext` INT NOT NULL AUTO_INCREMENT,
  `idpublication` INT NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`idtext`),
  INDEX `fk_text_publication1_idx` (`idpublication` ASC) VISIBLE,
  CONSTRAINT `fk_text_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`gazette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`gazette` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`gazette` (
  `idgazette` INT NOT NULL AUTO_INCREMENT,
  `object_key` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `idrecipient` INT NOT NULL,
  PRIMARY KEY (`idgazette`),
  INDEX `fk_gazette_recipient1_idx` (`idrecipient` ASC) VISIBLE,
  CONSTRAINT `fk_gazette_recipient1`
    FOREIGN KEY (`idrecipient`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`recipient` (`idrecipient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`publication_has_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`publication_has_like` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`publication_has_like` (
  `idpublication` INT NOT NULL,
  `iduser` INT NOT NULL,
  INDEX `fk_publication_has_like_publication1_idx` (`idpublication` ASC) VISIBLE,
  INDEX `fk_publication_has_like_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_publication_has_like_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_has_like_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`comment` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `created` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modified` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comment_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`publication_has_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`publication_has_comment` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`publication_has_comment` (
  `idpublication` INT NOT NULL,
  `idcomment` INT NOT NULL,
  INDEX `fk_publication_has_comment_publication1_idx` (`idpublication` ASC) VISIBLE,
  INDEX `fk_publication_has_comment_comment1_idx` (`idcomment` ASC) VISIBLE,
  CONSTRAINT `fk_publication_has_comment_publication1`
    FOREIGN KEY (`idpublication`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`publication` (`idpublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_has_comment_comment1`
    FOREIGN KEY (`idcomment`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`comment` (`idcomment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`comment_has_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`comment_has_like` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`comment_has_like` (
  `idcomment` INT NOT NULL,
  `iduser` INT NOT NULL,
  INDEX `fk_comment_has_like_comment1_idx` (`idcomment` ASC) VISIBLE,
  INDEX `fk_comment_has_like_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_comment_has_like_comment1`
    FOREIGN KEY (`idcomment`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`comment` (`idcomment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_has_like_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`recurring_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`recurring_payment` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`recurring_payment` (
  `iduser` INT NOT NULL,
  `idsubscription` INT NOT NULL,
  `amount` DECIMAL(5,2) NOT NULL,
  `start` TIMESTAMP NOT NULL,
  `end` TIMESTAMP NULL,
  INDEX `fk_recurring_payment_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_recurring_payment_subscription1_idx` (`idsubscription` ASC) VISIBLE,
  CONSTRAINT `fk_recurring_payment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recurring_payment_subscription1`
    FOREIGN KEY (`idsubscription`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`subscription` (`idsubscription`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`google_key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`google_key` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`google_key` (
  `idgoogle_key` BINARY(40) NOT NULL,
  `content` VARCHAR(2047) NOT NULL,
  `expiration` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idgoogle_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`firebase_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`firebase_has_user` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`firebase_has_user` (
  `idfirebase_user` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `uidfirebase` VARCHAR(63) NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  INDEX `fk_firebase_uid_user1_idx` (`iduser` ASC) VISIBLE,
  PRIMARY KEY (`idfirebase_user`),
  CONSTRAINT `fk_firebase_uid_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`default_family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`default_family` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`default_family` (
  `iduser` INT NOT NULL,
  `idfamily` INT NOT NULL,
  INDEX `fk_default_family_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_default_family_family1_idx` (`idfamily` ASC) VISIBLE,
  PRIMARY KEY (`iduser`),
  CONSTRAINT `fk_default_family_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_default_family_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2tehvmetpgbl28kakfx`.`family_invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2tehvmetpgbl28kakfx`.`family_invitation` ;

CREATE TABLE IF NOT EXISTS `b2tehvmetpgbl28kakfx`.`family_invitation` (
  `idfamily` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `inviter` INT NOT NULL,
  `approved` TINYINT NOT NULL DEFAULT 0,
  `accepted` TINYINT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_family_request_family1_idx` (`idfamily` ASC) VISIBLE,
  INDEX `fk_family_invitation_user1_idx` (`inviter` ASC) VISIBLE,
  CONSTRAINT `fk_family_request_family1`
    FOREIGN KEY (`idfamily`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`family` (`idfamily`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_invitation_user1`
    FOREIGN KEY (`inviter`)
    REFERENCES `b2tehvmetpgbl28kakfx`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `b2tehvmetpgbl28kakfx`.`subscription_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `b2tehvmetpgbl28kakfx`;
INSERT INTO `b2tehvmetpgbl28kakfx`.`subscription_type` (`idsubscription_type`, `name`, `price`) VALUES (1, 'Mensuel', 5.99);

COMMIT;

