version: "3.9"

services:
    server:
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: server
        environment:
            AUTORELOAD_PROGRAMS: "swoole"
            AUTORELOAD_ANY_FILES: 0
            MYSQL_ADDON_HOST: "mysql"
            MYSQL_ADDON_USER: "user"
            MYSQL_ADDON_PASSWORD: "devonly"
            MYSQL_ADDON_DB: "db"
            ISLOCAL: TRUE
            COMPOSER_ALLOW_SUPERUSER: 1
        # command: composer -d ./ install && composer clear-cache && php server.php
        restart: unless-stopped
        volumes:
            - ./server:/var/www
            - ./config:/var/www/config
            - ./app:/var/www/app
            - ./vendor/firebase/php-jwt/src:/var/www/app/jwt
            - ./public:/var/www/public
            - ./ressources/css:/var/www/public/css
            - ./ressources/fonts:/var/www/public/fonts
            - ./ressources/img:/var/www/public/img
            # - ./ressources/js:/var/www/public/js
            # - ./ressources/vendor:/var/www/public/vendor
        ports:
            - 8080:8080

    mysql:
        image: mysql:latest
        container_name: mysql
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "devonly"
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "devonly"
        ports:
            - 8081:3306

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        ports:
            - 8082:80
        environment:
            PMA_CONTROLUSER: "pma"
            PMA_CONTROLPASS: "devonly"
            PMA_HOST: "mysql"
            UPLOAD_LIMIT: "512M"

    # browserless:
    #     image: browserless/chrome:latest
    #     container_name: browserless
    #     restart: always
    #     ports:
    #         - 8083:3000
